OWNERS, README.md
Sorted owners file.
Fixed typos in README and changes for more inclusive language.
=> small fixes to owners and readme

Makefile, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go, pkg/pagerduty/types.go
- extract common functions into private functions
- make the AcknowledgeIncident endpoint smaller
- reduce the Incident struct size as it was not necessary
=> feat(ack): add new endpoint [OSD-9777]

pkg/README.md, pkg/aws/README.md, pkg/pagerduty/README.md
- move pagerduty docs to it's own folder
=> docs(aws): add docs

pkg/ocm/ocm.go
Enabling ability to get support role ARN for sts cluster
=> OSD-10119: added GetSupportRoleARN in ocm client

pkg/aws/aws.go
related to [OSD-10161](https://issues.redhat.com/browse/OSD-10161)
=> chore(gosec): fix gosec warning

.codecov.yml, .gitignore, .golangci.yml, Makefile, hack/codecov.sh, pkg/pagerduty/pagerduty.go
I don't know if this is useful, but I invested a few minutes and build a proper release pipeline + added tests with golangci.
If some of these steps are already covered by our jenkins pipeline I can remove them.
=> ci: add linting, code coverage and other useful checks

Makefile
fixes https://github.com/golangci/golangci-lint/issues/2374 on my machine
=> chore(makefile): bump golangci-lint

Dockerfile
=> chore(dockerfile): fix vuln

.golangci.yml, README.md, cadctl/cmd/cluster-missing/cluster-missing.go, pkg/pagerduty/pagerduty.go
this is super cool and it finds common misspells
=> chore(lint): add misspell linter

pkg/aws/aws.go
Just a minor function name fix
=> fix: spelling of function

Makefile, cadctl/cmd/cluster-missing/cluster-missing.go, pkg/aws/README.md, pkg/ocm/README.md, pkg/ocm/ocm.go, pkg/pagerduty/README.md
this embedmd works and it does pretty well
run 'make generate-markdown' to update all of the files
- updated OcmClient to be public for this to work
=> docs(embedmd): initial change [OSD-10209]

Dockerfile, cadctl/cmd/cluster-missing/cluster-missing.go, deploy/README.md, deploy/pipeline-run.yaml, deploy/task-cad-checks.yaml, go.mod, go.sum, pkg/aws/README.md, pkg/aws/aws.go, pkg/ocm/ocm.go, pkg/pagerduty/README.md, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/parsed-by-yq-webhook-payloads-from-test-pagerduty.yaml, pkg/services/assumerole/assumerole.go, pkg/services/chgm/chgm.go
Co-authored-by: Ramon Butter <rbutter@redhat.com>
=> feat(assumerole): add rolechain

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/services/assumerole/assumerole.go
Moved hardcoded values to ENV variable
=> Moved harded coded values to env

deploy/task-cad-checks.yaml
Updated to add new variables in task-checks yaml
=> Updated delpoyment for addtional variables

pkg/ocm/ocm.go
This PR implements boolean parsing
=> fix(ocm): parse bool instead of checking strings

CONTRIBUTING.md, Makefile, pkg/pagerduty/pagerduty.go
this will make the CONTRIBUTING.md cleaner, and is added to the 'make ci-check'
=> feat(make): error uniqueness check

hack/update-template/main.go, openshift/template.yaml
this PR makes the code be more like other operators, and fixes the image url that is used
=> chore(template): now force digest

CONTRIBUTING.md
This is a collection of information that can help to contribute and extend configuration-anomaly-detection
=> OSD-10193: added some more infos to contribution guide

hack/update-template/main.go
This is just a little PR to test if the image builds automatically.  It just fixes some parts of the documentation
=> fix: spelling in comments

OWNERS
Add more approvers for faster development cycles
=> chore: add more approvers

pkg/aws/aws.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
[osd-11731](https://issues.redhat.com//browse/osd-11731)
ListStoppedInstances updated to ListNonRunningInstances to reflect that it is not only stopped instances.
=> fix(aws): Change ListStoppedInstances to ListNonRunningInstances

pkg/aws/aws.go
[OSD-11754](https://issues.redhat.com//browse/OSD-11754)
=> fix(aws): Update logging to be clearer with stopped/non running instances

pkg/aws/aws.go, pkg/ocm/ocm.go, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/services/assumerole/assumerole.go, pkg/services/chgm/chgm.go
This commit fixes a few issues the GoLand IDE linter is highlighting.
=> fix: refactor code + fix documentation

pkg/services/chgm/chgm.go
[osd-11774](https://issues.redhat.com//browse/osd-11774)
=> fix(chgm): fix servicelog notes

pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go
[osd-11802](https://issues.redhat.com//browse/osd-11802)
=> fix(chgm): add error when 0 nonrunning instances are found

dashboards/configuration-anomaly-detection-dashboard.configmap.yaml
adds starter playground for cad dashboard
=> feat: add cad dashboard playground

deploy/tekton-pruner.yaml, openshift/template.yaml
Fixes: [OSD-11932](https://issues.redhat.com//browse/OSD-11932)
=> fix: add permissions to create jobs

dashboards/configuration-anomaly-detection-dashboard.configmap.yaml
updating the title and grafana directory so the dashboard can be found
=> fix: update cad dashboard title

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
This fixes the panels defaulting to the wrong datasource
=> fix: dashboard panel datasource

deploy/resource-quota.yaml, openshift/template.yaml
Fix: [OSD-11943](https://issues.redhat.com//browse/OSD-11943)
=> fix: introduce resourceQuota for pipelineRuns 

deploy/tekton-pruner.yaml, openshift/template.yaml
Fixes: [OSD-11946](https://issues.redhat.com//browse/OSD-11946)
We need more intel about cronjob failures. This commit tries to persist failed cronjobs.
=> fix: set restartPolicy to Never

deploy/tekton-pruner.yaml, openshift/template.yaml
We have a duplicate name for role and rolebinding
=> fix: rolebinding name

pkg/services/chgm/chgm.go
Fixes: [OSD-11973](https://issues.redhat.com//browse/OSD-11973)
=> feat: escalate incident if RH-SRE-* user is source of incident

pkg/services/chgm/chgm.go
Fixes: [OSD-11975](https://issues.redhat.com//browse/OSD-11975)
=> feat: Add Managed-OpenshiftInstaller Role to authenticated users

README.md
[osd-12094](https://issues.redhat.com//browse/osd-12094)
Adds CAD workflow to README
=> docs: add cad workflow to README

pkg/aws/aws.go
This commit introduces a mechanism to filter out events that have no
association to our cluster.
Fixes: [OSD-12138](https://issues.redhat.com//browse/OSD-12138)
=> fix: filter events with respect to cluster association

pkg/aws/aws.go
This fixes the time zone for the event polling
=> fix: change event polling time to UTC

deploy/README.md
[OSD-11376](https://issues.redhat.com//browse/OSD-11376)
Updates deploy readme to make it easier to follow.
=> docs: update deploy readme

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go
Completes: https://issues.redhat.com/browse/OSD-14647
---
These changes:
- remove an unnecessary check from the `investigateRestoredCluster` function, where recently terminated machines caused CAD's alert resolution investigation to fail
- introduce retry logic into CAD's `evaluateRestoredCluster` function, causing CAD to re-investigate clusters after a short delay. This provides time for them to fully recover from a stopped state, but is only carried out if no errors were encountered in the initial investigation.
- renames the alert generated by CAD when the investigation following CHGM alert resolution fails, based on feedback.
=> OSD-14647 - Reinvestigate clusters that have nodes missing when CHGM resolves

pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go
See https://issues.redhat.com/browse/OSD-16042:
**Why?**
We were missing some whitelisted roles/users that could cause customers to land in limited support.
**What?**
- Add missing users/roles in the whitelist
- Refactor for clarity
- Minimal documentation in code and link to full analysis and documentation
**Note:** the list was **only** expanded, meaning that the worst case here is that primary gets more alerts, the impact on customers should be only positive.
=> Fix(OSD-16042): whitelist additional roles and users

cadctl/cmd/investigate/investigate.go
When getting a cluster has gone missing alert for a gcp cluster, we currently escalate to on-call.
This change adds a check for any limited support reason on the cluster before this escalation happens and if it finds any CAD will silence the alert instead.
Solves https://issues.redhat.com/browse/OSD-16453
=> Add LS check for GCP clusters

pkg/ocm/ocm.go
Changing to uninstalling state as describe in the ticket [OSD-15971](https://issues.redhat.com/browse/OSD-15971)
=> Change LS function to skip uninstall instead of install states

pkg/services/ccam/ccam.go
**What?**
- Refactor access denied error check
=> Refactor access denied error check

pkg/services/ccam/ccam.go
**Why?**
In the recent refactor, I forgot to add early returns for the switch here. This results in us passing through and always ending up... where we should never end up.
=> Fix: add missing returns to ccam switch

pkg/services/cpd/cpd.go
**Why?**
We need to clarify what checks CAD runs, currently it just prints whether the network verifier passed or failed, which results in people running the `osdctl cpd` command.
Example new ouput:
=> Build CPD pagerduty note to contain all checks

cadctl/cmd/investigate/investigate.go, pkg/pagerduty/pagerduty.go
Do not print usage everytime there is an error
Add link to pagerduty incident
=> Improve log readibility

pkg/investigations/cpd/cpd.go
**Why?**
https://issues.redhat.com/browse/OSD-17726
The case that OCM sent a SL is a noop for SRE, thus the alert is now being silenced instead of escalated.
=> Silence CPD if OCM error is known and customer was notified via OCM

pkg/networkverifier/networkverifier.go
**What?**
Evaluate the errors (and evaluate them before further processing) in the network verifier package.
**Why?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x22be185]
goroutine 1 [running]:
github.com/openshift/configuration-anomaly-detection/pkg/networkverifier.initializeValidateEgressInput(0xc000858fc0, 0xc00017a5e0?, {0x310c460, 0xc000814280})
github.com/openshift/configuration-anomaly-detection/pkg/networkverifier/networkverifier.go:34 +0x45
```
=> fix: nilptr deref in networkverifier package

README.md, cadctl/cmd/investigate/investigate.go, cadctl/cmd/root.go, pkg/investigations/ccam/ccam.go, pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/cpd/cpd.go, pkg/investigations/investigation.go, pkg/metrics/README.md, pkg/metrics/metrics.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go, pkg/pagerduty/mock/pagerdutymock.go, pkg/pagerduty/pagerduty.go
Adds metrics for https://issues.redhat.com/browse/OSD-12591 
Small change to pass investigation resources to jumpRoles to have the context we need to set labels on the metric
I only added some metrics from the top of my mind, so please see this as WIP and add any thought on metric names, what metrics to capture and so on.
Needs testing as well but the metrics should not interfere with anything.
=> Add metric instrumentation

pkg/investigations/cpd/cpd.go, pkg/metrics/metrics.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go, pkg/pagerduty/mock/pagerdutymock.go, pkg/pagerduty/pagerduty.go
**What?**
This PR automates sending service logs for CPDs due to misconfigured routes.
https://issues.redhat.com/browse/OSD-18454
=> feat(OSD-18454): automate invalid routing SL for CPD

deploy/task-cad-checks.yaml, openshift/template.yaml
=> Set correct metric endpoint env

openshift/gateway-template.yaml
Fix app label so servicemonitor can pick up the service
=> Fix app label to configuration-anomaly-detection

cadctl/cmd/investigate/investigate.go
**What?** 
This PR fixes https://issues.redhat.com/browse/OSD-19366.
Changes: 
- added a check before running any investigations to make sure the cluster is in a state where we can run an investigation (currently just not "uninstalling").
- refactored the main logic to move the bigger pre-check if a cluster can have investigated into a new function
**Why?** 
Summary of the issue:
- When a cluster is mid-uninstall, the OCM API does not contain any `cluster deployment` objects. This resulted in CAD throwing 
```{
"level": "fatal",
"timestamp": "2023-10-21T00:59:25Z",
"msg": "could not retrieve Cluster Deployment for clusterid: failed to unmarshal client response () with error: unexpected end of JSON input",
"cluster_id": "clusterid",
"pipeline_name": …
```
=> fix(OSD-19366): check cluster state before proceeding with an investigation

Dockerfile
=> Upgrade base image to ubi-minimal 8.8

pkg/investigations/chgm/chgm.go
Implements https://issues.redhat.com/browse/OSD-20190
The servicelog that got prepared before now gets sent automatically.
Additionally, we now silence when DMS ('nosnch.in') is unreachable  on a missing cluster as we know it fires because it cannot reach DMS.
If the servicelog fails to send it falls back to posting the template on the incident, so SRE can manually send it.
=>  OSD-20190: automatically send network SL for chgms

Dockerfile
enable https://github.com/openshift/configuration-anomaly-detection/pull/271
=> Bump builder image to golang 1.21

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Updates dashboard to use the new prod instance post-migration.
=> OSD-21053: update dashboard to point at appsrep07ue1

pkg/investigations/ccam/ccam.go
The current stage CAD branch uses the latest backplane-cli, where the error message for assumeRoles to the customers AWS account was modified. CAD didn't handle this yet and does not know what to do with the installer assumerole failure. This PR adds handling for this.
=> Fix(OSD-23693): correctly handle backplane-cli errors for the used backplane-cli version

pkg/investigations/chgm/chgm.go
Removes two occurrences of duplicate emojis.
=> Fix some notes that don't use the noteWriter correctly

pkg/investigations/cpd/cpd.go
**What?** Handles a case causing a lot of noise due to failed pipelines specifically on staging where the installation fails due to an invalid configuration. This is not expected to happen on production
https://issues.redhat.com/browse/OSD-23210
=> fix(OSD-23210): handle nil clusterDeployments in rare installation cases

pkg/metrics/metrics.go
See https://github.com/prometheus/common/pull/576#issuecomment-1964952417
=> Fix prometheus dependency bump

Makefile, hack/pre-commit.sh
we have improved the makefile 
Lets try our workflows without this hook, we are open to add it back though, if it turns out its needed.
=> Remove precommit hook

pkg/investigations/cpd/cpd.go
https://issues.redhat.com/browse/OSD-25711
=> OSD-25711: Fix pagerduty note format of network verifier error error

deploy/pipeline-trigger.yaml, openshift/template.yaml
After having deploying Interceptor and testing, hooking the interceptor to tekton pipeline https://issues.redhat.com/browse/OSD-23695
=> hooking interceptor to tekton

pkg/aws/aws.go
This commit uses the Paginator for CloudTrail events, instead of just running a single query.
This should prevent missing events, even though it might mean longer runtimes for CAD in case of very many events matching stop/terminate events.
It also will only retry the event-gathering instead of the all the actions that follow on the event, to keep the retry-loop smaller.
=> [OSD-23494] Query all cloudtrail events for stop and terminate

test/generate_incident.sh
Adds short delay to allow pagerduty to create the incident
It now creates the payload file for you
=> Improve generate_incident script

Makefile
ci wont test anything otherwise
=> add make test target

interceptor/pkg/interceptor/pdinterceptor.go, interceptor/test/e2e.sh
Add `PD_SIGNATURE` header verification to interceptor to test on stage; step towards deprecating `X-Secret-Token` in favour of `PD_SIGNATURE`.
=> OSD-27752: Add PD_SIGNATURE verification to interceptor

README.md, cadctl/cmd/investigate/investigate.go, deploy/interceptor.yaml, deploy/task-cad-checks.yaml, hack/update-template/main.go, interceptor/main.go, interceptor/pkg/interceptor/pdinterceptor.go, openshift/template.yaml, pkg/logging/logging.go
This PR aims to allow for greater configuration of the log level, allowing for an env variable `LOG_LEVEL` to be set to control this. Further info added to the readme.
=> OSD-28718: Loglevel should be configurable

interceptor/test/e2e.sh
This PR aims to fix the failing interceptor e2e tests due to #368 (i.e. the interceptor now expects requests sent to be wrapped, however the e2e was not appropriately updated to handle this).
=> Fix interceptor e2e tests

pkg/investigations/pruningcronjoberror/metadata.yaml
https://issues.redhat.com/browse/OSD-28255 - CAD remediation pruningcronjob command
=> Added metadata.yaml in order to be able to test the pruning cronjob error investigation

pkg/investigations/CannotRetrieveUpdatesSRE/metadata.yaml
[OSD-18645](https://issues.redhat.com/browse/OSD-18645) - For local testing
=> Added metadata.yaml for CannotRetrieveUpdatesSRE for investigations

deploy/task-cad-checks.yaml, openshift/template.yaml
https://redhat-internal.slack.com/archives/C04PN0YCWGL/p1743167893510199
=> Remove deprecated cad-aws-secret ref

cadctl/cmd/investigate/investigate.go
This PR aims to fix an issue with `handleCADFailure()`, by making the function nil-safe. Currently, if the investigation returns before the investigation resources can be fully initialized, a nil pointer error will occur as the `handleCADFailure()` function relies on `investigation.Resources`.
=> OSD-28224: Add nil safety to handleCADFailure

test/set_stage_env.sh
Followup from https://github.com/openshift/configuration-anomaly-detection/pull/394
=> fix stage env script after removing aws creds from vault

deploy/tekton-pruner.yaml, hack/update-template/main.go, openshift/template.yaml
https://issues.redhat.com/browse/OSD-29266
We have not updated this image's version in a long time. This makes it configurable in the template, so we can easier keep track, possibly adding it to the promotion process.
=> Make tekton pruner image configurable via app-interface

openshift/template.yaml
https://issues.redhat.com/browse/SREP-67 
Third time is a charm, this time i verified that it works before hand ;)
=> Fix tekton resource pruner scc by using defaults

cadctl/cmd/investigate/investigate.go, pkg/ocm/ocm.go
Removes not used DEBUG options
Removes unused code.
- New investgations should be accompanied by unit tests and/or step-by-step manual tests in the investigation README.
- E2E testing is desired for actioning investigations. See README for more info on investigation graduation process.
=> Remove not used to debug option

cadctl/cmd/investigate/investigate.go, interceptor/main.go, pkg/investigations/chgm/chgm_test.go, pkg/logging/logging.go
Refactor the use of environment variables to eliminate the side effects.
The goal is to do minimal change keeping the functionality as is. 
The specific non-goal is to change the global nature of the logging package to introduce scopes.
It is also out of scope to replace RawLogger with the use of pointers. The change would snowball into more
changes across tests which would make this PR bigger than required for simple variable move.
Simplifies the configuration of the CAD
- New investgations should be accompanied by unit tests and/or step-by-step manual tests in the investigation README.
- E2E testing is desired for actioning investigations. See README for more info on investigation graduation process.
=> Moves environment variables to the beggining of the investigation and interceptor

test/e2e/configuration_anomaly_detection_tests.go
bug
Fixes E2E error, we tried to apply a configmap including the metadata (resourceversion) to restore an older version, so this could not work. 
Context:
```
[FAILED] failed test case: "[It] Configuration Anomaly Detection AWS CCS: clustermonitoringerrorbudgetburn"
Expected
<junit.Error>: 
[FAILED] Restore the backup ConfigMap
Unexpected error:
<*errors.StatusError | 0xc00063eaa0>: 
Operation cannot be fulfilled on configmaps "user-workload-monitoring-config": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on configmaps …
```
=> Fix: e2e tests should restore configmap without metadata to avoid conflict
