Makefile, cadctl/cmd/cluster-missing/cluster-missing.go, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go
- change `cluster-missing` endpoint to include basic PD token stuff
(rewritten 4 times already)
- errors were renamed/data changed for easier use
- makefile change to fix a build error
- moved to use `fmt.Fprint` instead of `w.Write` as it's cleaner and
doesn't require to cast to a byte array
- refactored the common errors together
related to [OSD-9777](https://issues.redhat.com/browse/OSD-9777)
=> feat(note): add new endpoint

go.mod, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go
- use mapstructure to convert between alert.Body to struct
- use gopkg.in/yaml to convert the 'notes' field to struct
=> feat(pagerduty): translate alert to externalid

CONTRIBUTING.md, pkg/aws/aws.go, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go, pkg/pagerduty/types.go
- add errors
- add private parser to local object
- put the alert type into 'types.go' (can move back to 'pagerduty.go' if
wanted)
- general un-nesting of errors
- fix CONTRIBUTING.md
=> feat(pagerduty): add getalerts endpoint

cadctl/cmd/cluster-missing/cluster-missing.go, deploy/README.md, deploy/pipeline.yaml, pkg/pagerduty/README.md, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go, pkg/pagerduty/parsed-by-yq-webhook-payloads-from-test-pagerduty.yaml
rust has a typos cli, which works better than misspell
this is what it found
https://github.com/crate-ci/typos
=> fix(typos): using typos

README.md
This adds just a badge for https://pkg.go.dev/
=> docs: add link to go pkg documentation

go.mod, go.sum, pkg/ocm/ocm.go, pkg/ocm/ocm_config.go, pkg/ocm/ocm_internal_test.go, pkg/ocm/ocm_suite_test.go
This commit pulls in the OCM config file handling again from the
ocm-cli repository. We do this, because the ocm-sdk-go provides
no way to load a JSON config file. They only handle YAML files.
=> fix(ocm): pull in OCM config file handling again

Makefile
This fixes the build issues in the final container image. The root cause is our security flags that do not work when the binary has been compiled statically. They heavily rely on libc (something we don't want in our containers).
=> fix(Dockerfile): build executable instead of a lib

pkg/aws/README.md, pkg/pagerduty/README.md, pkg/services/chgm/chgm.go
When we send notes into incidents we are currently dumping out a lot of json data that is not easy to digest.
This PR will make the notes human readable.
See playground link for example of output.
[OSD-11014](https://issues.redhat.com//browse/OSD-11014)
https://go.dev/play/p/2h3BMITpdAk
=> feat(chgm): Make notes/logging human readable for CAD events

Dockerfile
This sets the red hat owned base image for golang instead of the docker hub alpine one
=> fix: set redhat owned docker image

deploy/serviceaccount.yaml, openshift/template.yaml
The role and role-binding are for the pipelinerun and not for the eventListener. Let us rename them accordingly.
=> fix(deploy): Rename role and role-binding

deploy/pipeline-trigger.yaml, deploy/pipeline.yaml, deploy/serviceaccount.yaml, deploy/task-cad-checks-secrets-aws.yaml, deploy/task-cad-checks-secrets-ocm-client.yaml, deploy/task-cad-checks-secrets-pd.yaml, deploy/task-cad-checks.yaml, openshift/template.yaml
We shall not specify namespaces, because otherwise it's impossible to deploy to cad and cad-stage namespaces with the different pipelines.
For dev deployments we can either do `oc apply -f -n cad` or set the current project as context in oc
via `oc project cad`.
=> fix: remove namespaces

pkg/ocm/ocm.go
strconv.ParseBool raises an error when debugMode is empty, thus
we have to set it to false if the value is empty.
Fix: [OSD-11695](https://issues.redhat.com//browse/OSD-11695)
=> fix(ocm): Fix debugMode for OCM

cadctl/cmd/cluster-missing/cluster-missing.go, deploy/task-cad-checks.yaml, openshift/template.yaml, pkg/pagerduty/README.md, pkg/services/chgm/chgm.go
[OSD-11712](https://issues.redhat.com//browse/OSD-11712)
Makes status messages visible in pod logs.
Also a few minor typo fixes.
=> fix(chgm): make status messages visible in pod logs

pkg/services/assumerole/assumerole.go
hence we have to use ID() to retrieve the correct region the cluster.
Fixes: [OSD-11734](https://issues.redhat.com//browse/OSD-11734)
=> fix: cluster.Region().Name() returns an empty string

pkg/aws/aws.go, pkg/services/chgm/chgm.go
This commit refactors a few positions in the code that triggers the GoLand linter.
=> refactor: simplify regex + minor refactoring

deploy/tekton-pruner.yaml, openshift/template.yaml
resource pruning is not enabled in the app-sre clusters, and we are not able to annotate
the namespace, hence we are going to use a cronjob for pruning instead.
Please do not merge this. I have to get in contact with app-sre first. This PR is intended as last resort, when everything else is not possible.
Also, I am not sure if the serviceaccount in our namespace has enough permissions to do this. :/ If not this will not work as well.
=> feat: add resource-pruner cronjob

deploy/tekton-pruner.yaml, openshift/template.yaml
This sets a new tekton-cli image and fixes the 404 not found error.
Fixes: [OSD-11909](https://issues.redhat.com//browse/OSD-11909)
=> fix: set new tekton-cli image

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/ocm/ocm.go, pkg/services/ccam/ccam.go, pkg/services/ccam/ccam_suite_test.go, pkg/services/chgm/chgm.go
CCAM provides a way to send an alert if the cluster credentials
are missing. This is the case, when the assumeRole call
fails with an "Access Denied" response.
Fixes: [OSD-11736](https://issues.redhat.com//browse/OSD-11736)
=> feat: implement CCAM (Cluster Credentials Are Missing)

deploy/tekton-pruner.yaml, openshift/template.yaml
Remove the image pull secret and use the image in quay.io instead.
Related to: [OSD-11910](https://issues.redhat.com//browse/OSD-11910)
=> fix: use tkn-client image in quay

deploy/tekton-pruner.yaml, openshift/template.yaml
Running the cronjob just once per day makes it difficult to debug failed jobs.
Let's change this to every hour and keeping just 20 cad-check pods.
=> fix: change schedule for pruner cronjob

deploy/tekton-pruner.yaml, openshift/template.yaml
The cronjobs needs at least permissions to list pipelineruns.
I have added get and watch as well.
=> fix: add more permissions to the cronjob

hack/update-template/main.go, openshift/template.yaml
We cannot dynamically set namespaces within app-sre/interface, hence
try to remove them from the rolebinding completely and just let
k8s deploy it into the correct namespace
Fixes: [OSD-11954](https://issues.redhat.com//browse/OSD-11954)
=> fix: do not set namespace in rolebindings

pkg/services/chgm/chgm.go
[OSD-11939](https://issues.redhat.com//browse/OSD-11939)
Updates the notes so the UserName and IssuerUserName fields are not printed when empty. The ServiceLog Sent field will display 'None' when empty.
=> fix(chgm): Clean up PD notes when fields are empty

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/services/ccam/ccam.go
This adds a missing nested error for AssumeRole failures
=> fix: be more verbose about AssumeRole failures

pkg/aws/aws.go, pkg/aws/aws_test.go
Amazon AWS tokens are used for API throttling. Every call to an API endpoint
costs us one token. Before this commit, our listAllInstancesAttribute
exhausted all our available AWS tokens, this lead to AWS throttling us.
The new function does only ONE request instead of one request for every token.
In this request we gather a maximum of 1000 results for a 2hour timeframe.
This should be enough for us to handle CHGM alerts
=> fix: remove AWS token depletion

cadctl/cmd/cluster-missing/cluster-missing.go
This improves logging for cluster credentials are missing alerts.
=> fix: improve logging for CCAM

pkg/aws/aws.go
This prints all foreign events. All, events that can't be associated with our instance list.
=> fix: print foreign events

pkg/services/chgm/chgm.go
To reduce confusion when no SL is sent, specifically state that manual SRE investigation is needed.
=> fix: make notes more specific when no SL is sent

pkg/aws/aws.go
was looking over some of the old code, I wrote...
and believe to found a bug, that will cause an infinity loop of calling the AWS API for the case the instances are returned on several pages.  
The nextToken has to be stored in the Request, as it is done [here](https://github.com/evalphobia/aws-sdk-go-wrapper/blob/0ad241a2f698d46f056aee89f79dc5624cd5cdba/cloudtrail/client.go#L64).
Great to see though that things are still going forward with CAD.
=> iterate over pages on pageinated ListInstance results for aws pkg

Dockerfile
This commit is supposed to fix vulnerabilities in our current CAD generation
depending on ubi 8.6
Fixes: [OSD-12602](https://issues.redhat.com/browse/OSD-12602)
=> fix(Dockerfile): security vulnerabilities

OWNERS, go.mod
Step [12.3.3 ](https://github.com/openshift/ops-sop/blob/master/security/leaver_process.asciidoc#1233-review-users-owners-permissions) of the leaver process SOP includes removal from our openshift repos. Hence, this PR serves the removal of Christian Rebischke.
=> OHSS-14525 Removal of leaver shibumi from owners

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/pagerduty/pagerduty.go
Adds branching logic to `cadctl`'s `cluster-missing` subcommand so that PagerDuty webhooks can updated to accommodate limited support testing.
=> OSD-12961 - Add empty logic for 'incident.resolved' payloads so webhooks can be updated

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/ocm/ocm.go, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
Completes: https://issues.redhat.com/browse/OSD-12961; https://issues.redhat.com/browse/OSD-12957
---
These changes add logic to update the Limited Support status for a cluster based on the state of it's Cluster Has Gone Missing (CHGM) alert. 
When the CHGM alert fires initially, CAD evaluates the cluster and determines whether the alert was caused by a customer action. In cases where this is determined to be the case, the cluster is placed into Limited Support. Otherwise, the alert is forwarded based on the environment's PagerDuty escalation policy.
When the CHGM alert resolves, CAD once again evaluates the cluster and determines whether it is sufficiently healthy to be removed from Limited Support. This investigation consists of the following: 1) checking that all EC2 instances owned by …
=> OSD-12961; OSD-12957 - Integrate Limited Support into CAD's CHGM logic

deploy/task-cad-checks.yaml, openshift/template.yaml
Completes: https://issues.redhat.com/browse/OSD-13901
---
These changes modify the payload generation logic, to avoid evaluating the quoting used within.
This is necessary because the string `Dead Man's Snitch` frequently appears in these payloads. When there's an odd number of these present in the data, bash interprets this as a mismatched quotation and the cluster evaluation never starts.
=> OSD-13901 - Use heredocs when generating payload to avoid quoting errors

deploy/task-cad-checks.yaml, openshift/template.yaml
Removes single-quotes that were erroneously left in during https://github.com/openshift/configuration-anomaly-detection/pull/136.
=> OSD-13901 - Removed quotes surrounding payload data

README.md, pkg/services/ccam/ccam.go
When a CHGM alert fires due to missing credentials (CCAM service), a limited support reason is posted. This PR will also send this CHGM alert to SilentTest escalation policy so Primary will not get unnecessary pages.
=> Send CCAM incidents to SilentTest when limited support

pkg/ocm/ocm.go
Removes duplicate `Action Required` prefixes from Limited support summaries. 
This prefix is automatically added by OCM when emailing a customer, and should not be included in CAD's own reasons.
=> Removed redundant prefix from Limited Support summary lines

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/ocm/ocm.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/services/chgm/mock/interfaces.go
These changes do the following:
- Avoid duplicating CHGM LS reasons if the cluster already has one
- Allow CCAM alerts to be silenced, even if a cluster already has a CCAM alert
=> Additional bugfixes for CAD-LS integration

pkg/services/chgm/chgm.go
Using strings.Contains() instead of strings.HasPrefix() to properly catch operator roles that are allowed to stop instances.
=> Ensure operator role is allowed to stop instances

cadctl/cmd/cluster-missing/cluster-missing.go, pkg/ocm/ocm.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
https://issues.redhat.com/browse/OSD-14636
---
Adds logic to the `investigateStartedInstances` function to ignore clusters with a limited support status.
=> Don't evaluate restored cluster if in limited support

deploy/tekton-pruner.yaml, openshift/template.yaml
**What?**
Keep tekton pipelines for a week instead of pruning everything but the last 20 every hour.
**Why?**
We need access to pipeline run logs and don't want them to be pruned away before investigating.
=> Keep pipelines for a week

deploy/resource-quota.yaml, openshift/PipelinePruning.md, openshift/template.yaml
Since we keep runs longer after the change in https://github.com/openshift/configuration-anomaly-detection/pull/151 
we need to also increase the quota.
We ran into this issue on stage today where CAD was unable to spawn new runs, checking the event listener, we could see quota errors and deleting some PipelineRuns manually fixed the issue.
=> Increase pipeline quota to 1000

pkg/ocm/ocm.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
Updated the node count check to differentiate between master, infra and worker. Included the machine pools workers in the workers count.
The investigation of started instance gives an error only if there's a mismatch in the count of master or infra nodes.
=> OSD-14629 - CAD node/instance count check can misfire

pkg/services/chgm/chgm.go
[OSD-15256](https://issues.redhat.com//browse/OSD-15256)
The osdmanagedadmin user does not always contain a suffix, sometimes it can be just "osdmanagedadmin". This fixes the authorized user check.
=> fix: osdmanagedadmin user prefix

pkg/services/chgm/chgm.go
**Why?**
When checking the cloudtrail events of unauthorized users, we iterate through them and set the `output.UserAuthorized = false` flag. However, even after finding an unauthorized user, we keep on looping and overwrite the `output.User` data. This results in `output` containing the wrong user along with the unauthorized flag, which makes logs and the pagerduty notes point investigators in the wrong direction.
**What?**
Return early once we find an unauthorized user, as to not overwrite the `output` data.
I think we definitely need a total revamp of `output` and the way we print it. Go ctx comes to mind to easily add data on the fly and pass it through the whole investigation ;) However, I don't want to interfere to much with the currently pending PRs, so I'm keeping this fix as …
=> fix: don't overwrite unauthorized user data

cadctl/cmd/investigate/investigate.go
Quick fix for a bug introduced with the refactor.
After putting a cluster in limited support for ccam there was no return statement, failing on a subsequent call to non existent aws.Client and failing the pipeline.
Now it should return nil when it put a cluster in ccam limited support and end the run correctly.
=> fix: Exit and return success when posting CCAM limited support

.golangci.yml
**Why?**
Linter timeout (default 1 min) currently fails. 
**What?**
Increase linter timeout.
=> Increase timeout for golang ci lint

cadctl/cmd/investigate/investigate.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/utils/utils.go
**What?**
- refactor retries function to remove duplicate defaults and global variables (commit 1)
- Add pagerduty note when infrastructure is unsupported for investigation (commit 2)
**Why?**
- General maintainance
- Make it clear why CAD didn't run on a CHGM for GCP clusters
=> Add note for unsupported infra

pkg/ocm/ocm.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
**What?**
- Limited CAD CHGM resolve investigation to clusters that CAD put into LS itself, as we everything else is a NOOP for CAD. 
- Renamed `LimitedSupportReasonExists` to `IsInLimitedSupport` to make the function names less confusing
**Why?**
This change allows us to use less resources for CAD pipelines and removes unnecessary long pipeline runs.
https://redhat-internal.slack.com/archives/C04PN0YCWGL/p1676498065888859?thread_ts=1676463360.065339&cid=C04PN0YCWGL
=> Limited CHGM alert resolve investigations to clusters that have the CHGM LS reason

pkg/ocm/ocm.go
**What?**
Add the limited support reason to the log message of `Found no limited support reason to remove`, as this could lead to confusion when we remove several reasons.
**Why?**
Reduce confusion when going through CAD logs
=> Output the limited support reason that couldn't be removed

pkg/ocm/ocm.go, pkg/services/chgm/chgm.go
**Why?**
LS post logging was outside of the LS post function, moved it to the function to make sure we always log it.
=> Log limited support reason for all limited support posts

cadctl/cmd/investigate/investigate.go, pkg/services/chgm/chgm.go
**Why**?
See https://redhat.pagerduty.com/incidents/Q3DIQB8OOFEBVS/timeline
We don't clarify what CAD does in the note, it looks like a second investigation.
=> Make resolve investigation logging less confusing

pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go
The role 'OrganizationAccountAccessRole' is used by SRE in case of non CCS clusters and by the user otherwise.
This PR changes the isUserAllowedToStop function to respect the clusters flavor and return false when 'OrganizationAccountAccessRole' was used on a CCS cluster.
=> OSD-15569 : Add CCS/nonCCS differentiation

pkg/pagerduty/pagerduty.go, pkg/services/ccam/ccam.go
**Why?**
CAD tried to silence alerts that are already resolved.
**What?**
CAD doesn't try to silence alerts that are already resolved anymore (for CCAM).
=> Don't silence resolved alerts

pkg/pagerduty/pagerduty.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/chgm/mock/interfaces.go
**What?**
- Renamed variables
- Added helper functions for future work, clarified what the functions do in their names
- Remove additional wrapper for `moveToEscalationPolicy`
=> Minor refactor on pagerduty.go

cadctl/cmd/investigate/investigate.go
**What?**
- Directly escalate alerts not handled by CAD.
**Why?**
- We are currently not directly escalating GCP alerts, affecting our mean time to resolve for GCP CHGM.
Jira: [OSD-16111](https://issues.redhat.com//browse/OSD-16111)
=> Escalate directly in case cloud provider or alert is not supported

.golangci.yml, Makefile, cadctl/cmd/investigate/investigate.go, cadctl/main.go, hack/update-template/main.go, pkg/aws/aws.go, pkg/investigation/investigation.go, pkg/ocm/ocm.go, pkg/ocm/ocm_config.go, pkg/pagerduty/pagerduty.go, pkg/services/assumerole/assumerole.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/utils/utils.go
**What?**
Dynamically downloads golangci-lint v1.52.2. If golangci-lint is already installed, it uses the already installed golang-ci.lint.
This fixes issues when using a higher go version that doesn't fit the previously old hardcoded golangci-lint version of the makefile.
**Why?**
This results in nasty errors and blocks https://issues.redhat.com/browse/OSD-15137 because of a desync in the lint and go version.
=> Upgrade golangci-lint to v1.52.2 and use local version if existing

deploy/pipeline.yaml, deploy/task-cad-checks.yaml, openshift/template.yaml, pkg/services/logging/logging.go, pkg/services/networkverifier/networkverifier.go
**What?**
- Fixes passing of parameter pack to zapLogger (previously the passing resulted in extra brackets `[]` for log messages)
- Converts leftover print statements to logged messages
- Pipeline name should now properly be passed down to the taskrun by tekton
**Why?**
https://issues.redhat.com/browse/OSD-16113
=> Fix pipeline id and logging

.editorconfig, .golangci.yml, Makefile, cadctl/cmd/investigate/investigate.go, hack/pre-commit.sh, hack/update-template/main.go, pkg/aws/aws.go, pkg/aws/aws_test.go, pkg/ocm/ocm_config.go, pkg/pagerduty/errors.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go, pkg/services/ccam/ccam.go, pkg/services/chgm/chgm.go, pkg/services/chgm/chgm_test.go, pkg/services/cpd/cpd.go, pkg/services/networkverifier/networkverifier.go, pkg/services/networkverifier/networkverifier_test.go
Ticket: [OSD-16112](https://issues.redhat.com/browse/OSD-16112)
- Adds linters to the golangci-lint config
- Adds an editorconfig to enforce usage of tab over spaces
- Adds a pre-commit hook created by the Makefile
The following lint errors raised by https://github.com/nakabonne/nestif remain up for discussion:
```
cadctl/cmd/investigate/investigate.go:103:2: `if !cloudProviderSupported` has complex nested blocks (complexity: 5) (nestif)
if !cloudProviderSupported {
^
pkg/services/chgm/chgm.go:57:2: `if res.UserAuthorized` has complex nested blocks (complexity: 7) (nestif)
if res.UserAuthorized {
^
pkg/services/chgm/chgm.go:135:2: `if res.Error != ""` has complex nested blocks (complexity: 5) (nestif)
if res.Error != "" {
```
We could set the complexity to a value of 10 to prevent …
=> OSD-16112: Improve linting

pkg/aws/aws.go, pkg/aws/mock/aws.go, pkg/services/cpd/cpd.go
This adds the rest of the checks that are run with 'osdctl cluster cpd' command to the cpd investigation for https://issues.redhat.com/browse/OSD-13697
Why: this will allow us to remove the highlighting for the cpd command in CPDS sop and eventually we should be able to deprecate it completely.
osdctl implementation https://github.com/openshift/osdctl/blob/master/cmd/cluster/cpd.go#L69 
I did not change the escalation behavior, so everything should still get escalated but with some more specific information.
Tested manually.
Please keep it a draft for now. I am still testing the BYOVPC subnet validation.
=> Add remaining checks from 'osdctl cluster cpd' to cpd investigation

cadctl/cmd/investigate/investigate.go, pkg/ocm/ocm.go
Fixes bug with empty external cluster ids on CPDs.
We do not need to do another call to ocm to get the cloud provider as we already have the full cluster object at that point.
=> fix: OSD-17489 empty external cluster id

cadctl/cmd/investigate/investigate.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go
**What?**
- Always default to internal ID. This removes some duplicate code that re-queried OCM to get a cluster's internal ID, when we already had it. 
- Fully fixes https://issues.redhat.com/browse/OSD-17489, as we would run into the next error when we query something with the external ID again. 
**Why?**
https://issues.redhat.com/browse/OSD-17489
With the addition of CPD, we can't use the external ID as default anymore, as a lot of clusters in the early installing stage don't have that ID yet.
=> Normalize default cluster ID to internal-id

go.mod, go.sum
Thix fixes a timeout bug when quay.io is found as a blocked url
I did not move the zap logger package manually,i called  go get network verifier and go decided its now a direct import ;)
=> Bump networkverifier from 0.2.2 to 0.3.1

pkg/services/cpd/cpd.go
When multiple routing tables are missing a default route we only want to post the service log once.
As we do not populate the servicelog with details about which subnet is missing which route, we can skip posting the individual subnets with the service log.
Closes https://issues.redhat.com/browse/OSD-17516
=> OSD-17516: Return early when checking default routes

cadctl/cmd/investigate/investigate.go
**Why?**
With the recent addition of the staging app-sre service, we can now handle stage CPDs. 
**What?**
This PR adds the stage service name to the struct that handles getting the internal ID differently.
=> OSD-17220: Add CPD stage service in service switch

cadctl/cmd/investigate/investigate.go, pkg/investigations/investigation.go, pkg/investigations/silencealerts/silencealerts.go, pkg/logging/logging.go, pkg/networkverifier/networkverifier.go, pkg/pagerduty/mock/pagerdutymock.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go
**What?**
Implement [OSD-17456](https://issues.redhat.com//browse/OSD-17456).
CAD can now handle SilenceAlerts (hypershift inhibition alerts). It will resolve all old alerts when a SilenceAlert is triggered.
The next steps would be to add orchestration rules to all hypershift pd services that route only the SilenceAlerts to CAD.
**Why?**
We use alert inhibition as silencing method for hypershift. The issue with this is that inhibiting alerts does not result in active alerts being resolved. This is very frustrating e.g. when starting to work on an alert but the cluster ends up being mid uninstallation.
=> OSD-17456 Add alert handling for hypershift SilenceAlerts

cadctl/cmd/investigate/investigate.go
**What?**
Log the string variant of the `cloudProvider` instead of the struct.
**Why?**
```
{"level":"info","timestamp":"2023-08-17T05:45:32Z","msg":"Unsupported cloud provider: &{%!s(uint32=7) gcp /api/clusters_mgmt/v1/cloud_providers/gcp  }"
```
=> fix: logging of unsupported cloud provider

cadctl/cmd/investigate/investigate.go, pkg/investigations/ccam/ccam.go, pkg/investigations/chgm/chgm.go, pkg/investigations/cpd/cpd.go, pkg/metrics/metrics.go
Switch WithLabelValues to GetMetricWithLabelValues to avoid panics
Remove wrongly copy pasted label list on servicelogPerpared metric
=> hotfix: metric panic and labels

cadctl/cmd/investigate/investigate.go
**What?**
- Moves logic to decode `cluster_id` after checking if the alert is supported by CAD. 
**Why?**
Some unsupported alerts don't contain the `cluster_id`, e.g. the AVO alerts on the `app-sre-alertmanager` service. This causes CAD pipelines to exit ungracefully. 
Therefore, we need to move the logic to decode the cluster_id after the check if an alert is supported.
=> fix: check if alert is supported before decoding cluster_id

.github/dependabot.yml, .gitignore
This would allow a PR to be created automatically in this repo whenever osd-network-verifier has a new version
=> use dependabot to automatically update osd-network-verifier

deploy/task-cad-checks.yaml, openshift/gateway-template.yaml, openshift/template.yaml
This adds a new template for deploying an aggregation pushgateway
It will allow for the metrics to get pushed to this gateway and subsequently scraped by app-sre's prometheus.
The template should get added to our cad-saas file in app interface and use the mirrored aggregation-pushgateway image on quay. ( See corresponding app-interface change )
=> Add template for pushgateway deployment

pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_hibernation_check.go, pkg/investigations/chgm/chgm_hibernation_check_test.go, pkg/investigations/chgm/chgm_test.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go
When clusters are in hibernation for >= 30 days the internal certificates used by kubelet will have expired and CSRs must be approved by hand to get the cluster into a healthy state again.
=> [OSD-18424] Add new check if cluster recently woke up.

openshift/gateway-template.yaml
The pushgateway image is mirrored in a private repository so we need a pullsecret to be able to pull the image.
This specifies that the deployment uses the serviceaccount 'pushgateway' defined in app-interface.
Also fixes the default parameter for the image path but that has no effect as we overwrite in our saas file currently.
=> Specify service account with quay.io pullsecret

cadctl/cmd/investigate/investigate.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go, pkg/pagerduty/pagerduty.go
https://issues.redhat.com/browse/OSD-18650
**What?**
- this adds a check in CAD for clusters using the new flow and escalates them if the clusters aren't in limited support
**Why?**
- new AWS backplane flow will be promoted to production this week or the following, we do not support this flow so we must make sure that we don't accidentally put clusters in limited support due to missing access
=> feat(OSD-18650): [stopgap] support alerts from clusters with new backplane flow

pkg/investigations/chgm/chgm.go
Increasing the servicelog metrics here  fell through the cracks.
We want to know on how many chgm alerts cad prepared a servicelog.
https://issues.redhat.com/browse/OSD-12591
=> metrics: Add missing chgm instrumentation

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Update/Create grafana dashboard including
- SLO for successful runs (90%)
- average pipeline duration (should stay way below 15 min)
- Stats on the alerts and actions taken
Part of https://issues.redhat.com/browse/OSD-10961
=> Update grafana dashboard

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
The dashboard does not get deployed. I think we need to remove the id for grafana to load it properly.
=> dashboard: remove id to fix deployment

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Fix wrong title and uid from grafana playground.
Sorry for the noise.
=> dashboard: fix title and uid

dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Fixes the SLO query by selecting only cad-check pods. Otherwise we are off by a few pods (gateway, pruner...).
Updates the defaults to production environment with a 30d time range
=> dashboard: fix SLO, change default to prod and 30d

go.mod, pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go
I collapsed go.mod's two indirect import sections and ran go mod tidy as well. Didn't add any imports or stuff like that.
[OSD-19451](https://issues.redhat.com//browse/OSD-19451)
=> Allow CAD to process CloudTrail EventVersions >=1.08

cadctl/cmd/investigate/investigate.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go
**What?**
- Skip the CAD aws access compatibility check for non sts clusters (this was causing pipeline failures, as non-sts clusters have no sts support role).
- Reorders the logic if an investigation should be started on a cluster. The previous logic was getting too complicated with the additional STS logic, so I split it up which causes code duplication but is easier to read.
**Why?**
```
could not query sts support role from ocm: status is 400, identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '123456': Retrieving SRE support role arn is only available for AWS STS clusters only
```
=> fix(OSD-19596): skip aws access compatibility check for non-sts clusters

pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go
**What?**
Fixes a small bug where the note would get posted twice. Changed to follow the idiom of adding everything to the note and posting once done with all checks.
=> Post network verifier run failure at the end of investigation

pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/cpd/cpd.go
**What?**
CAD sends service logs with the "Error" severity, which does not exist. I updated the severities to match the OCM guidelines. 
**Why?**
https://issues.redhat.com/browse/OSD-22320
=> OSD-22320: Update SL severities to match OCM guidelines

openshift/SRVKP-437-workaround-template.yaml
Adds workaround for pipelines-scc missing the seccompProfile: https://issues.redhat.com/browse/SRVKP-4372
=> OSD-22496: add scc workaround

deploy/pipeline-trigger.yaml, deploy/task-cad-checks.yaml, deploy/tekton-pruner.yaml, openshift/template.yaml
Add resource requests and limits to all containers.
Infered some sensible values from production metrics. 
The TaskRuns only get a limit. This way the resource requests are set to the same value as the limit and we get QoS class Guaranteed. As we do not retry the TaskRuns, we should make them be evicted last. 
Closes: https://issues.redhat.com/browse/OSD-22524
=> Set resource limits to all containers

deploy/task-cad-checks.yaml, openshift/template.yaml
We use tekton v1beta1 and the field is 'resources' instead of 'computeResources'
https://tekton.dev/docs/pipelines/tasks/#defining-steps
=> Fix invalid tekton step definition

go.mod, go.sum, pkg/aws/aws.go, pkg/aws/mock/aws.go, pkg/networkverifier/networkverifier.go
This checks that a subnet does not have a route to `0.0.0.0/0` to an internet gateway. This usually denotes a public subnet.
Currently this keeps the old check for MapPublicIpOnLaunch as well if no IGW route is found.
=> [OSD-22536] Add new routetables check for public subnets.

pkg/investigations/chgm/chgm.go, pkg/investigations/cpd/cpd.go, pkg/notewriter/notewriter.go, pkg/notewriter/notewriter_test.go
This PR refactors to use a `NoteWriter` allowing to have a set format for notes we add to pagerduty.
=> maint: add notewriter instead of building strings via sb directly

cadctl/cmd/investigate/investigate.go, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn_test.go, test/generate_incident.sh
https://issues.redhat.com/browse/OSD-23312
This PR showcases how CAD could use kube api with an example implementation of the remediation to https://issues.redhat.com/browse/OCPBUGS-33863. 
The implementation is hidden behind a `CAD_EXPERIMENTAL_ENABLED` flag that we will enable on staging after enabling kube-api access in https://issues.redhat.com/browse/OSD-23311.
=> PoC: Investigate ClusterMonitoringErrorBudgetBurn due to a misconfigured UWM configmap

pkg/investigations/ccam/ccam.go
Fixes a copy paste error in https://github.com/openshift/configuration-anomaly-detection/pull/285:
I had copy pasted and forgot to update the string.
This is now tested on a cluster where the pipeline fails, so it will work.
=> Fix(OSD-23693): wrong string to determine installer assumerole failure

Makefile
```
make help
Usage:
make <target>
Global:
all                                                 Generate, build, lint, test all subprojects
build                                               Build all subprojects in this repository 
lint                                                Lint all subprojects
cadctl:
cadctl                                              Run all targets for cadctl (generate, build, test, lint, generation)
generate-cadctl                                     Generate mocks for cadctl
build-cadctl                                        Build the cadctl binary
lint-cadctl                                         Lint cadctl subproject
test-cadctl                                         Run automated tests for cadctl
Interceptor:
interceptor …
```
=> Maint: makefile better split into categories

.golangci.yml, cadctl/cmd/investigate/investigate.go, go.mod, go.sum, pkg/investigations/ccam/ccam.go, pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/chgm/util.go, pkg/investigations/chgm/util_test.go, pkg/investigations/cpd/cpd.go, pkg/investigations/investigation.go, pkg/ocm/mock/ocmmock.go, pkg/ocm/ocm.go
This PR updates CAD's CHGM behavior to put clusters that block PD/DMS into limited support. We need to do this as we can't guarantee SLA in those cases.
=> fix(OSD-24257): put clusters in LS if DMS/PD is blocked

pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/chgm/util.go, pkg/investigations/chgm/util_test.go
This fixes the previous PR, we now escalate alerts with PD blocked to customers anyway as it is otherwise very confusing: we still need to investigate alerts if only PD is blocked (not DMS).
=> fix(OSD-24257): put clusters in LS if PD is blocked

pkg/investigations/ccam/ccam.go, pkg/investigations/ccam/ccam_test.go
**What?**
Adds another string that points at the customer misconfiguring their role to the list of strings that result in limited support. 
**Why?**
We recently bumped backplane-cli, this changed the format of error strings bubbled up from OCM. This adds another of these new strings to CAD's handling.
=> Add backplane cli string of installer role policy changed/removed

pkg/networkverifier/networkverifier.go
In the network verifier library, `securityGroupId` has long been deprecated in favor of `securityGroupIds`. This PR moves us over to use the latter so we aren't using a deprecated field.
=> Don't use deprecated 'securityGroupId' in verifier library

README.md, pkg/aws/aws.go
The tag format has slightly changed in 4.16 causing a failure to find the security group and subnet to populate the network verifier.
"As of 4.16, some downstream component is causing the subnet tag kubernetes.io/cluster/<infra_id> to show as "shared" instead of "owned" now, even for fresh installs in clean AWS accounts. As far as the network verifier is concerned, we probably don't actually care about the value of this tag, just that it exists.
Also in 4.16, security group have changed the name tag format from  `<infra_id>-master-sg` to `<infra_id>-controlplane`. 
We need to check for both now."
Fixes https://issues.redhat.com/browse/OSD-24458 
Tested in stage against 4.15 and 4.16 cluster.
Note to the reviewer: There is a similar PR for osdctl here …
=> Update security group and subnet tag filters for 4.16

interceptor/pkg/interceptor/pdinterceptor.go
Self explanatory - this logger message is for when we find a mapping, but the text says the opposite.
=> Fix typo in log output when mapping is found in interceptor

pkg/aws/aws.go
As the slice is no longer a pointer, checking len() works in both cases:
- len(nil-slice) == 0
- len(empty-slice) == 0
See: https://go.dev/play/p/ah-hRMCmEWk
=> Replace nil check with len()

pkg/investigations/ccam/ccam.go, pkg/investigations/ccam/ccam_test.go
**What?**
Handles the scenario where customers remove the `GetRole` permission of the installer role, which OCM requires to get the support role. With this PR, CAD will handle this scenario the same way as the other cases where customers broke permissions needed to access the cloud environment. 
**Why?**
This is a customer caused error that CAD can handle as "customer broke permissions" scenario route a notification to the customer.
=> fix(OSD-25690): pipeline failure for removed GetRole permission on installer

go.mod, go.sum, interceptor/go.mod, interceptor/go.sum, pkg/investigations/chgm/chgm_test.go, pkg/networkverifier/networkverifier.go
This incorporates version `v1.1.2` of `osd-network-verifier`, which includes a breaking change to the `ValidateEgressInput` struct type. This additionally includes an update to fetching the machine image ID to no longer use the deprecated `GetAMIForRegion` function.
For some reason, I had to update the expectations of the `chgm` suite, although I didn't fundamentally change any AWS calls, things started failing. Would love if someone had an answer here.
Closes https://github.com/openshift/configuration-anomaly-detection/pull/315
=> OSD-25886 | Integrate osd-network-verifier v1.1.2

deploy/interceptor.yaml, openshift/template.yaml
Adds liveness probe to CAD interceptor, so SRE can know when the interceptor service for CAD is down. This [PR](https://github.com/openshift/managed-cluster-config/pull/2252) will alert SRE when two or more CAD interceptor pods are crashloopoing.
https://issues.redhat.com/browse/OSD-23696
=> [OSD-23696-Add-CAD-liveness-probe] Add liveness probe for interceptor

deploy/pipeline-trigger.yaml, openshift/template.yaml
We need this to move CAD to a private cluster:
- LB service directly pointing at tekton event listener
- event listener is responsible for TLS termination
- added certificate needed by evente listener (ClusterIssuer should already be there)
=> feat(OSD-27020): Tekton eventlistener to terminate TLS

.github/dependabot.yml
Our sub module interceptor requires to be updated ( might just be go mod tidy? ) when the outer mod receives updates.
See https://github.com/dependabot/dependabot-core/issues/6678
=> Make dependabot work with multinode repo due to interceptor

deploy/pipeline-trigger.yaml, openshift/template.yaml
This change adds a loadbalancer service to the pipeline trigger. Exposes the internal cluster to the pagerduty service. Only pagerduty IPs are allowed to access the pipeline trigger.
IPs might change, see:
- https://developer.pagerduty.com/docs/9a349b09b87b7-webhook-i-ps
=> Add loadbalancer service to the pipeline trigger

interceptor/pkg/interceptor/pdinterceptor.go
This PR makes the interceptor logs less verbose.
=> cleanup: verbosity of interceptor logs

pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/util.go, pkg/investigations/chgm/util_test.go
Solves failing to post LS on network misconfigs https://issues.redhat.com/browse/OSD-27300
The limitedsupport message defined here https://github.com/openshift/managed-notifications/blob/master/osd/limited_support/egressFailureLimitedSupport.json
does no longer include the blocked URLs, so we remove it here as well.  
Since networkverifier >= 1.0 the errors include parenthesis which break the current behavior ( as LS api does not allow for them, see https://issues.redhat.com/browse/OCM-13249 )
=> Align network misconfig LS message

pkg/investigations/clustermonitoringerrorbudgetburn/metadata.yaml
See [SDE-3270](https://issues.redhat.com//browse/SDE-3270) for backplane remediations. 
We use the rbac in the metadata to create rbac on cluster and let cad use the kube-api for its investigation.
=> Add metadata file to first investigation using backplane remediations

deploy/interceptor.yaml, deploy/task-cad-checks.yaml, hack/update-template/main.go, openshift/template.yaml
This PR routes the CAD_EXPERIMENTAL_ENABLED flag through the deployment to allow enabling and disabling it via the saas file in app-interface.
=> Feat: route CAD_EXPERIMENTAL_ENABLED flag

README.md, cadctl/cmd/investigate/investigate.go, deploy/task-cad-checks-secrets-pd.yaml, interceptor/pkg/interceptor/pdinterceptor.go, interceptor/test/e2e.sh, openshift/template.yaml, pkg/investigations/ccam/ccam.go, pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/investigations/cpd/cpd.go, pkg/pagerduty/mock/pagerdutymock.go, pkg/pagerduty/pagerduty.go, pkg/pagerduty/pagerduty_test.go
Previously, CAD had a separate escalation policy for the prod-deadmanssnitch and app-sre-alertmanager services. To escalate to SRE, it re-assigned to the SRE Platform Oncall escalation policy.
Now CAD is the first level in the SRE Platform Oncall escalation policy, if it re-assigns to that same policy, we introduce a 15 min delay before SRE receive the alert.
Instead of re-assigning to the escalation policy, CAD should use real escalation: escalating to the next level.
Additionally, this PR:
- updates naming of the pagerduty term `alert` to `incident` for consistency with pagerduty
- removes unused functions in `pagerduty.go`
Needed for: https://issues.redhat.com/browse/SDE-4177 
Implements: https://issues.redhat.com/browse/OSD-27979
=> Feat(OSD-27979): remove escalation policy and replace by escalating to the next level

pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/k8s/client.go, test/set_stage_env.sh
Add the cleanup call to backplane-api to delete investigation RBAC
After the investigation has ended we need to cleanup the created RBAC.
We will have garbage collection via managed-cluster-config in case this
fails. One can also delete it manually with `ocm backplane remediation delete <clusterid> <investigation>` .
=> Cleanup k8s

cadctl/cmd/investigate/investigate.go, pkg/investigations/ccam/ccam.go, pkg/investigations/ccam/ccam_test.go, pkg/investigations/chgm/chgm.go, pkg/investigations/chgm/chgm_test.go, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/investigations/cpd/cpd.go, pkg/investigations/registry.go
https://issues.redhat.com/browse/OSD-28725
---
This PR just updates the name of each investigation package's primary struct to a standard name, `Investigation`.
The goal is to create a consistent package standard, and to make object initialization more idiomatic. ie -
```
&clustermonitoringerrorbudgetburn.CMEBB{}
```
becomes
```
&clustermonitoringerrorbudgetburn.Investigation{}
```
=> OSD-28725 - Rename investigation structures to standard name 'Investigation'

pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
https://issues.redhat.com/browse/OSD-19770 
This PR graduates ClusterMonitoringErrorBudgetBurn to non-experimental
=> Feat(OSD-19770): graduate ClusterMonitoringErrorBudgetBurn to non-experimental

pkg/investigations/machineHealthCheckUnterminatedShortCircuitSRE/metadata.yaml
https://issues.redhat.com/browse/OSD-28525
---
Fixes typo in `MachineHealthCheckUnterminatedShortCircuitSRE`'s clusterrole which prevents the investigation from GET-ing/LIST-ing machine objects.
=> OSD-28525 - Fix typo in clusterrole

README.md, hack/bootstrap-investigation.sh
https://issues.redhat.com/browse/OSD-28775
---
This PR updates the instructions and bootstrapping logic for new investigations to require the test process be preserved for future use.
Specifically, bootstrapping a new investigation will add a `testing/` directory to hold the files and scripts needed to recreate the investigation conditions on a test cluster. Additionally, a placeholder README for the testing procedure is also templated out with the expectation that it will be used to document investigation testing steps for future maintainers.
=> OSD-28775 - Add basic instructions to include test objects for new investigations

.github/dependabot.yml
We had some issues with our multi go mod setup for the interceptor, but this configuration might work.
We had tried to fix it with commit https://github.com/openshift/configuration-anomaly-detection/commit/68f13da267a8cf1c4e7032b1727d801878818162 
But either by mistake or some unknown reason we removed it here https://github.com/openshift/configuration-anomaly-detection/pull/353
=> Fix dependabot for gomod updates

pkg/investigations/machineHealthCheckUnterminatedShortCircuitSRE/metadata.yaml
https://issues.redhat.com/browse/OSD-28525
---
Rescopes the existing permissions for the `MachineHealthCheckUnterminatedShortCircuitSRE` investigation remediation serviceaccount - specifically makes `machine.machine.openshift.io` permissions namespace-scoped instead of cluster-scoped.
Adds additional cluster-scoped permission to GET nodes
=> OSD-28525 - Update permissions for MachineHealthCheckUnterminatedShortCircuitSRE investigation

cadctl/cmd/investigate/investigate.go, interceptor/pkg/interceptor/pdinterceptor.go, interceptor/test/e2e.sh
This PR aims to fix an issue with the interceptor e2e not adding the env signature variable, thus unreadable to the interceptor. It also corrects the investigation's name in logging.
=> Fix interceptor e2e env issue & investigation name logging

README.md, test/generate_incident.sh
Remove the need to export pd token, by using cads own token. 
Redo the corresponding Readme steps.
=> Simplify local testing steps

cadctl/cmd/investigate/investigate.go, hack/bootstrap-investigation.sh, pkg/investigations/chgm/chgm.go, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/investigations/cpd/cpd.go, pkg/investigations/investigation/investigation.go
This PR aims to add handling to ensure that investigation failures (and notes collected up until failure) are always posted to PagerDuty, as currently some exceptions/errors result in empty notes.
=> OSD-28224 - cad should always post failures to the incident notes

README.md, deploy/pipeline-trigger.yaml, deploy/task-cad-checks-secrets-pd.yaml, openshift/template.yaml
This PR aims to deprecate the `x-secret-token`, as CAD now utilizes the `X-PagerDuty-Signature` token in it's place.
Followup to https://github.com/openshift/configuration-anomaly-detection/pull/363
=> OSD-27752: Deprecate x-secret-token

pkg/investigations/cpd/cpd.go
The egress urls can contain spaces, thus we need to double quote the URLs string in the template we provide to consumers.
=> fix: ClusterProvisioningDelay servicelog templating

go.mod, go.sum, interceptor/go.mod, interceptor/go.sum
This PR addresses [OSD-29354](https://issues.redhat.com/browse/OSD-29354) by updating CAD's osd-network-verifier dependency from v1.2.1 to v1.2.3 in order to prevent issues with missing/outdated AMIs
=> Bump osd-network-verifier to v1.2.3

pkg/networkverifier/networkverifier.go
We tend to see a lot of clusters that have CAD run against them hit timeouts with egress.
After reviewing, I noticed we had set the timeout to 2 seconds which felt pretty tight.
I have updated that value to be 5 seconds, which lines up with what OCM uses to perform pre-cluster creation network verification. I think unifying on a default (in osd-network-verifier next) will ensure we are consistent about this across tools and services.
=> OSD-29402: Increase the default network-verifier timeout from 2s to 5s

cadctl/cmd/investigate/investigate.go, pkg/pagerduty/mock/pagerdutymock.go, pkg/pagerduty/pagerduty.go
https://issues.redhat.com/browse/OSD-29424
---
These changes update the PagerDuty incident title after an investigation completes to more visibly indicate when CAD has run. The goal is to reduce the potential for duplicated work as a result of on-call not seeing the investigation notes CAD attaches to the incident.
The title is only updated once: subsequent CAD runs will not re-attach the `[CAD Investigated]` prefix to the incident, in order to keep titles useful across multiple investigation attempts
=> OSD-29424 - Update PD incident title after investigation

cadctl/cmd/investigate/investigate.go
Fixes minor bug where the `pagerDutyTitlePrefix` const wasn't being used to prefix the PagerDuty incident title upon investigation completion.
=> OSD-29424 - Bugfix to use `pagerdutyTitlePrefix` instead of hardcoded string when updating incident title

go.mod, pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go, pkg/investigations/insightsoperatordown/insightsoperatordown.go, pkg/k8s/client.go, pkg/k8s/errors.go, pkg/k8s/errors_test.go, pkg/k8s/scheme.go
This PR adds handling for degraded api errors we can receive when calling backplane to create our kubeconfig/permission mappings. I also split up the k8sclient package for separation of concerns.
=> Maint: handle degraded api when creating k8sclient

pkg/investigations/machineHealthCheckUnterminatedShortCircuitSRE/metadata.yaml
Adds an additional object to the `machinehealthcheckUnterminatedShortCircuit` investigation's `openshift-machine-api` role, so that the investigation can retrieve the machinehealthcheck object it's investigating
=> OSD-28525 - Additional permission for CAD to retrieve machinehealthchecks on-cluster

go.mod, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre_test.go, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/metadata.yaml, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/recommendation.go, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/README.md, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/srep-worker-healthcheck_machinehealthcheck.yaml, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/unstoppable_pdb.yaml, pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/unstoppable_workload.yaml, pkg/investigations/registry.go, pkg/investigations/utils/machine/machine.go, pkg/investigations/utils/machine/machine_test.go, pkg/investigations/utils/node/node.go, pkg/investigations/utils/node/node_test.go, pkg/k8s/scheme.go, test/generate_incident.sh
https://issues.redhat.com/browse/OSD-28525
---
These changes introduce the initial implementation for the `machineHealthCheckUnterminatedShortCircuitSRE` alert. The alert investigation takes the following steps:
- Retrieves the machines managed by any failling machinehealthcheck object. Machines & nodes that are failing which are otherwise un-managed by a machinehealthcheck that is short-circuited (ie - masters) are not investigated
- Machines that are deleting will have their node checked to see if it's stuck draining. At the moment, this check is imperfect: once the ability to query metrics is introduced, we can more precisely confirm what workloads are blocking a node drain based on the `pods_preventing_node_drain` metric
- Machines that are in a failed state will have their …
=> OSD-28525 - Initial implementation for MachineHealthCheckUnterminatedShortCircuitSRE investigation

pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
This PR fixes the parameter passed to k8s client setup to match the folder name containing `metadata.yaml`.
=> Fix: machinehealthcheckunterminatedshortcircuitsre k8s client setup

cadctl/cmd/investigate/investigate.go
This PR gets rid of all the non-0 exiting pipelines for clusters that don't exist (e.g. integration cluster ids in staging). This is mostly to suppress failed pipeline noise, should not happen on production.
=> Fix: ignore non-existant clusters

pkg/investigations/aitest/README.md, pkg/investigations/aitest/metadata.yaml, pkg/investigations/aitest/testing/README.md
This PR adds full read permissions for a new investigation that will stay experimental for now and doesn't map to a real alert.
=> Experimental POC: add k8sgpt permissions

openshift/template.yaml
https://issues.redhat.com/browse/SREP-67
Switch to runAsUser & runAsGroup 65534
`Warning  FailedCreate  56s (x42 over 36m)  job-controller  Error creating: pods "tekton-resource-pruner-29117400-" is forbidden: unable to validate against any security context constraint`
=> Fix security context for tekton resource pruner

openshift/template.yaml
https://issues.redhat.com/browse/SREP-67
Follow up to https://github.com/openshift/configuration-anomaly-detection/pull/440 as user and group was not enough :D 
`Warning  FailedCreate  56s (x42 over 36m)  job-controller  Error creating: pods "tekton-resource-pruner-29117400-" is forbidden: unable to validate against any security context constraint`
=> Add seccompProfile RuntimeDefault to tekton pruner job

pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
Updates the `MachineHealthCheckShortCircuitUnterminatedSRE` investigation to indicate it's no longer an experimental feature, and should run in prod.
=> OSD-28525 - make MachineHealthCheckShortCircuitUnterminatedSRE investigation non-experimental

test/e2e/configuration_anomaly_detection_test.go
```
15:21:47 test/e2e/configuration_anomaly_detection_test.go:93:55: too many arguments in call to awsinternal.NewClient
15:21:47 	have (string, string, string, string)
15:21:47 	want ("github.com/aws/aws-sdk-go-v2/aws".Config)
15:21:53 Error: building at STEP "RUN CGO_ENABLED=0 GOFLAGS="-mod=mod" go test ./test/e2e -v -c --tags=osde2e -o /e2e.test": while running runtime: exit status 1
15:21:53 make: *** [test/e2e/project.mk:31: e2e-image-build-push] Error 1
15:21:53 Build step 'Execute shell' marked build as failure
15:21:53 Finished: FAILURE
```
=> fix e2e test blocking build

go.mod, go.sum, interceptor/go.mod, interceptor/go.sum
This is needed as the previous version filtered the IP Whitelist and blocked CAD.
=> Update backplane-cli dependency.

cadctl/cmd/investigate/investigate.go, interceptor/pkg/interceptor/pdinterceptor.go
This minor PR fixes the non-functioning experimental enabled flag. For context see https://redhat-internal.slack.com/archives/C04PN0YCWGL/p1747756748758649?thread_ts=1747754723.175979&cid=C04PN0YCWGL
=> Fix obtaining of "experimental enabled" env variable

.github/workflows/auto-tidy-interceptor.yml
Implemented a github action to fix the [OSD-28972](https://issues.redhat.com//browse/OSD-28972).
This will automatically detect if there is any change in go.mod from root/cadctl and auto tidy the interceptor go.mod and updates the PR
=> OSD-28972: Updated github actions workflow to support dependabot PRs

openshift/template.yaml
Unlike what I thought: service monitors cannot handle the numeric value of a port.
=> SREP-207: Naming cad-interceptor-service service port so it can be referenced by the ServiceMonitor

pkg/ocm/ocm.go, test/generate_incident.sh
https://redhat-internal.slack.com/archives/CB53T9ZHQ/p1748452131912789
The issue in the original code is in the endpoint used to get the creator account information. We originally used the subscription API endpoint, which doesn't return all the information we need to make this change. I have updated the code to take the subscription id we get and hit the api again afterwards, this time using the accounts API endpoint.
I also used this PR to add a line to the generate incident script for the "UpgradeConfigSyncFailureOver4HrSRE Critical (1)" alert which I inadvertently left out of a previous PR.
=> Fix bug SREP-652: User's incorrectly reporting as not banned.

README.md, test/launch_local_env.sh
In `test/launch_local_env.sh`, the check for the `client_id` could fail with a "unary operator expected" error if the `jq` command produced an empty result. This would happen if the config file path was invalid or the `client_id` key was missing, causing the script to crash abruptly.
By wrapping the command substitution in double quotes, the comparison remains syntactically valid even with an empty string. This allows the script to fail gracefully and display its own helpful error message instead of exiting with a shell error.
Additionally, a stray quotation mark is removed from a command example in the README.
=> Prevent script failure on empty client_id

cadctl/cmd/investigate/investigate.go, pkg/investigations/precheck/precheck.go, pkg/investigations/precheck/precheck_test.go
This PR fixes two things:
- we now exit early and gracefully if access protection is unknown. This prevents errors later in the logic with little context.
- we exit gracefully again if prechecks determine a cluster doesn't need to be investigated. 
- New investgations should be accompanied by unit tests and/or step-by-step manual tests in the investigation README.
- Actioning investigations should be locally tested in staging, and E2E testing is desired. See [README](https://github.com/openshift/configuration-anomaly-detection/blob/main/README.md#graduating-an-investigation) for more info on investigation graduation process.
=> Fix: pre-check exits early on unknown access protection

test/e2e/configuration_anomaly_detection_tests.go
Enhancement
This PR has been created to fix the OCM configuration for CAD E2E tests to enable the configuration to run in local as well as be able to run in the E2E pipeline
Attached is the successful test case example 
[SREP-1164_tests.txt](https://github.com/user-attachments/files/21853494/SREP-1164_tests.txt)
=> Fixing OCM configuration loading using OCM config
